repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: local
  hooks:
    - id: malformed-event-dates
      name: Malformed event date check
      entry: |
        bash -c\
        `malformed_event_dates=$(grep -Er --files-without-match '^eventdate: [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} [-+][0-9]{4}$' _events)\
        if [ -n "${malformed_event_dates}" ]; then\
        echo "Malformed event date in:" >&2\
        echo "${malformed_event_dates}" >&2\
        exit 1
        fi'
      language: system
      types: [file]
      files: \.(markdown|md)$
      pass_filenames: false
