extends: existence
message: "Do not use level 1 headings (#) in blog posts. Instead, add the 'title' to the front matter."
link: https://github.com/opensearch-project/project-website/blob/main/BLOG_GUIDE.md#front-matter
level: error
scope: heading.h1
tokens:
  - '.*'